import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { ArrowUpRight } from "lucide-react";
import { editorialImages } from "@/lib/images";

export const metadata: Metadata = { title: "About", description: "Discover the point of view behind our bridal and modest fashion collections." };

export default function AboutPage() { return <div className="shell"><div className="page-intro"><p className="eyebrow">About us</p><h1>A quiet point of view.</h1><p>We create considered bridal and modest fashion for women who value beauty that feels personal.</p></div><section className="about-split pb-32"><div className="about-image"><Image src={editorialImages.about} alt="Editorial portrait from the collection" fill sizes="(max-width: 680px) 100vw, 50vw" className="object-cover" /></div><div className="about-copy"><p className="eyebrow">Who we are</p><h2>Our story</h2><p>We are a fashion company dedicated to creating elegant bridal and modest fashion collections.</p><p>Our collection brings together timeless wedding dresses, refined bridal pieces and contemporary hijabs, with a focus on thoughtful design, beautiful materials and modern femininity.</p><p>Through our work, we hope to create pieces that feel elegant, comfortable and meaningful for women around the world.</p></div></section><section className="section-cream -mx-[calc((100vw-100%)/2)] px-[calc((100vw-100%)/2)] py-24"><div className="shell about-split"><div className="about-copy"><p className="eyebrow">Our philosophy</p><h2>Bridal & modest, in conversation.</h2><p>We believe elegance is expansive. It can be quiet or expressive, traditional or new, and always rooted in how a piece makes a woman feel.</p><Link className="button button-dark mt-6" href="/contact">Contact us <ArrowUpRight size={14} /></Link></div><div className="about-image"><Image src={editorialImages.dualHijab} alt="Modest fashion styling detail" fill sizes="(max-width: 680px) 100vw, 50vw" className="object-cover" /></div></div></section></div>; }
