"use client";

import Link from "next/link";
import type { Language } from "@/components/i18n/LanguageProvider";
import { useLanguage } from "@/components/i18n/LanguageProvider";
import { siteConfig } from "@/config/site";

type SupportCopy = {
  title: string; intro: string; contact: string; contactLead: string; include: string; includeItems: string[]; sensitive: string; reply: string;
  gettingStarted: string; gettingItems: string[]; saving: string; savingText: string; important: string; savingItems: string[];
  ai: string; tryThis: string; aiItems: string[]; aiText: string; tryOn: string; bestResult: string; tryOnItems: string[]; tryOnText: string; permission: string;
  sharing: string; sharingText: string[]; delete: string; deleteText: string[]; privacyBefore: string; privacyAfter: string; privacyLink: string;
  company: string; operatedBy: string; lastUpdated: string;
};

const copy: Record<Language, SupportCopy> = {
  en: {
    title: "Support", intro: "Luverila Hijab Designer helps creators draw hijab concepts, build multi-view designs, generate AI visualizations, try designs on an authorized portrait, and prepare images for sharing.",
    contact: "Contact Support", contactLead: "For help, email", include: "Please include:", includeItems: ["Your device model and iOS or iPadOS version", "The Luverila Hijab Designer app version", "A short description of what happened", "A screenshot of the error, if appropriate"], sensitive: "Please do not email passwords, verification codes, payment information, government identification, API keys, or private photos that are not needed to investigate the issue.", reply: "We aim to respond within 2–3 business days.",
    gettingStarted: "Getting Started", gettingItems: ["Start a new design or open a saved project.", "Draw and arrange elements using brushes, colors, materials, patterns, layers, and front, side, or back views.", "Save the editable project to the on-device Works area.", "Export a PNG when you need a finished image.", "Use AI visualization or virtual try-on only when you want the selected design and optional portrait to be processed by an AI service."],
    saving: "Saving and Restoring Designs", savingText: "Design projects are primarily stored on your device. Use Save Project to create or update an editable work in the Works area. You can also export an editable project file as a separate backup.", important: "Important:", savingItems: ["Deleting the app, clearing app data, losing the device, or restoring the device may remove locally stored projects.", "A PNG is a finished image and cannot restore all editable layers.", "Keep exported project backups for important work."],
    ai: "AI Generation Is Unavailable or Fails", tryThis: "Try the following:", aiItems: ["Confirm that your device has a stable internet connection.", "Keep the app open while the image is being generated.", "Try again later if the service is busy.", "Reduce very large imported images or complex reference material.", "If available, try the standard generation option before high-quality generation."], aiText: "AI generation can occasionally fail or produce an unexpected result. A generated image is a visual concept, not a guarantee of the final product's fit, construction, color, or fabric behavior.",
    tryOn: "Virtual Try-On and Face Similarity", bestResult: "For the best result:", tryOnItems: ["Use a clear, well-lit portrait with one person", "Keep the face unobstructed and use a natural camera angle", "Use a design view that clearly shows the hijab construction", "Enable identity protection when you want the person to remain recognizable", "Keep eye enlargement and lip-shape adjustments at moderate strength"], tryOnText: "AI image editing may still change facial details, pose, fabric placement, or lighting. If a result does not look like the person, do not share it as an accurate representation. Try again with stronger identity protection or fewer facial beauty edits.", permission: "Only upload a portrait when you are the person shown or have that person's permission.",
    sharing: "Exporting and Sharing", sharingText: ["You can export finished images and prepare square, portrait, or story-format sharing images. Files saved to Photos or Files remain there until you delete them using the relevant Apple app.", "If system sharing is unavailable, download the sharing image and share it from Photos or Files."],
    delete: "Delete a Project or Photo", deleteText: ["To remove a saved project, open the Works area and choose Delete for that project.", "The original portrait selected for virtual try-on is not automatically added to an editable project. To remove downloaded or exported images, delete them separately from Photos or Files and, if needed, from Recently Deleted.", "The current release does not require a Luverila account. Therefore, there is no account profile to delete. If a future release introduces accounts, this page will provide an account-deletion method before that feature is launched."], privacyBefore: "For a privacy request, contact", privacyAfter: "for details.", privacyLink: "App Privacy Policy",
    company: "Company Information", operatedBy: "Luverila Hijab Designer is operated by:", lastUpdated: "Last updated: August 8, 2026"
  },
  zh: {
    title: "应用支持", intro: "Luverila Hijab Designer 帮助创作者绘制头巾概念图、构建多视图设计、生成 AI 视觉效果、在获得授权的人像上试戴设计，并制作可分享的图片。",
    contact: "联系支持团队", contactLead: "如需帮助，请发送邮件至", include: "请在邮件中附上：", includeItems: ["设备型号以及 iOS 或 iPadOS 版本", "Luverila Hijab Designer 应用版本", "问题的简要说明", "如适用，附上错误截图"], sensitive: "请不要通过电子邮件发送密码、验证码、付款信息、政府签发的身份证件、API 密钥，或排查问题不需要的私人照片。", reply: "我们将在 2–3 个工作日内回复。",
    gettingStarted: "开始使用", gettingItems: ["新建设计，或打开一个已保存的项目。", "使用画笔、颜色、材质、图案、图层以及正面、侧面或背面视图进行绘制和排版。", "将可编辑项目保存到设备上的作品区域。", "需要成品图片时导出 PNG 文件。", "仅当你希望所选设计和可选人像由 AI 服务处理时，才使用 AI 视觉呈现或虚拟试戴。"],
    saving: "保存和恢复设计", savingText: "设计项目主要存储在你的设备上。使用“保存项目”在作品区域中新建或更新可编辑作品。你也可以导出可编辑项目文件作为单独备份。", important: "重要提示：", savingItems: ["删除应用、清除应用数据、丢失设备或恢复设备，可能会移除本地存储的项目。", "PNG 是成品图片，无法恢复所有可编辑图层。", "请为重要作品保留导出的项目备份。"],
    ai: "AI 生成功能不可用或失败", tryThis: "请尝试以下操作：", aiItems: ["确认设备具有稳定的网络连接。", "图片生成期间请保持应用打开。", "若服务繁忙，请稍后重试。", "减小过大的导入图片或复杂参考素材。", "如可选，请先尝试标准生成选项，再使用高质量生成。"], aiText: "AI 生成偶尔可能失败或产生意外结果。生成的图片仅为视觉概念，并不保证最终实体产品的合身度、制作工艺、颜色或面料表现。",
    tryOn: "虚拟试戴和人脸相似度", bestResult: "为获得更好的效果：", tryOnItems: ["使用清晰、光线充足且仅含一人的人像照片", "保持面部无遮挡，并使用自然的拍摄角度", "使用能清晰显示头巾结构的设计视图", "希望人物保持可识别时，请启用身份保护", "将眼睛放大和唇形调整控制在适中强度"], tryOnText: "AI 图像编辑仍可能改变面部细节、姿势、面料位置或光线。如果结果看起来不像该人物，请不要将其作为准确展示分享。请尝试更强的身份保护，或减少面部美化编辑。", permission: "仅当你是照片中的本人，或已获得该人物许可时，才可上传人像。",
    sharing: "导出和分享", sharingText: ["你可以导出成品图片，并制作方形、竖版或故事格式的分享图片。保存到“照片”或“文件”的文件会一直保留，直到你使用相应的 Apple 应用将其删除。", "如果系统分享不可用，请下载分享图片，再从“照片”或“文件”中进行分享。"],
    delete: "删除项目或照片", deleteText: ["要移除已保存的项目，请打开作品区域，并为该项目选择“删除”。", "用于虚拟试戴的原始人像不会自动添加到可编辑项目。要移除下载或导出的图片，请分别从“照片”或“文件”中删除；必要时也请从“最近删除”中移除。", "当前版本不需要 Luverila 账户，因此没有可删除的账户资料。若未来版本引入账户功能，本页面将在功能上线前提供账户删除方式。"], privacyBefore: "如需提出隐私请求，请联系", privacyAfter: "了解详情。", privacyLink: "应用隐私政策",
    company: "公司信息", operatedBy: "Luverila Hijab Designer 的运营方为：", lastUpdated: "最后更新：2026 年 8 月 8 日"
  },
  es: {
    title: "Soporte", intro: "Luverila Hijab Designer ayuda a los creadores a dibujar conceptos de hiyab, crear disenos con varias vistas, generar visualizaciones con IA, probar disenos en un retrato autorizado y preparar imagenes para compartir.",
    contact: "Contactar con soporte", contactLead: "Para obtener ayuda, escribe a", include: "Incluye:", includeItems: ["El modelo de tu dispositivo y la version de iOS o iPadOS", "La version de Luverila Hijab Designer", "Una breve descripcion de lo ocurrido", "Una captura del error, si corresponde"], sensitive: "No envies por correo contrasenas, codigos de verificacion, informacion de pago, identificaciones oficiales, claves API o fotos privadas que no sean necesarias para investigar el problema.", reply: "Nuestro objetivo es responder en un plazo de 2 a 3 dias laborables.",
    gettingStarted: "Primeros pasos", gettingItems: ["Inicia un diseno nuevo o abre un proyecto guardado.", "Dibuja y organiza elementos con pinceles, colores, materiales, patrones, capas y vistas frontal, lateral o trasera.", "Guarda el proyecto editable en el area Works del dispositivo.", "Exporta un PNG cuando necesites una imagen final.", "Usa la visualizacion con IA o la prueba virtual solo cuando quieras que un servicio de IA procese el diseno seleccionado y el retrato opcional."],
    saving: "Guardar y restaurar disenos", savingText: "Los proyectos se almacenan principalmente en tu dispositivo. Usa Guardar proyecto para crear o actualizar un trabajo editable en el area Works. Tambien puedes exportar un archivo de proyecto editable como copia de seguridad.", important: "Importante:", savingItems: ["Eliminar la app, borrar sus datos, perder el dispositivo o restaurarlo puede eliminar proyectos almacenados localmente.", "Un PNG es una imagen final y no puede restaurar todas las capas editables.", "Conserva copias exportadas de los proyectos importantes."],
    ai: "La generacion con IA no esta disponible o falla", tryThis: "Prueba lo siguiente:", aiItems: ["Comprueba que el dispositivo tenga una conexion estable a internet.", "Manten la app abierta mientras se genera la imagen.", "Intentalo de nuevo mas tarde si el servicio esta ocupado.", "Reduce imagenes importadas muy grandes o materiales de referencia complejos.", "Si esta disponible, prueba la opcion de generacion estandar antes de la de alta calidad."], aiText: "La generacion con IA puede fallar ocasionalmente o producir un resultado inesperado. Una imagen generada es un concepto visual, no una garantia del ajuste, la confeccion, el color o el comportamiento del tejido de un producto final.",
    tryOn: "Prueba virtual y similitud facial", bestResult: "Para obtener mejores resultados:", tryOnItems: ["Usa un retrato claro, bien iluminado y con una sola persona", "Mantén el rostro despejado y utiliza un angulo de camara natural", "Usa una vista de diseno que muestre claramente la construccion del hiyab", "Activa la proteccion de identidad si quieres que la persona siga siendo reconocible", "Mantén los ajustes de agrandamiento de ojos y forma de labios en una intensidad moderada"], tryOnText: "La edicion de imagen con IA aun puede cambiar rasgos faciales, pose, colocacion del tejido o iluminacion. Si el resultado no se parece a la persona, no lo compartas como una representacion precisa. Prueba una proteccion de identidad mas fuerte o menos retoques faciales.", permission: "Solo sube un retrato si eres la persona que aparece en el o tienes su permiso.",
    sharing: "Exportar y compartir", sharingText: ["Puedes exportar imagenes finalizadas y preparar imagenes cuadradas, verticales o para historias. Los archivos guardados en Fotos o Archivos permanecen alli hasta que los elimines con la aplicacion de Apple correspondiente.", "Si no esta disponible la funcion de compartir del sistema, descarga la imagen y compartela desde Fotos o Archivos."],
    delete: "Eliminar un proyecto o una foto", deleteText: ["Para eliminar un proyecto guardado, abre el area Works y elige Eliminar para ese proyecto.", "El retrato original seleccionado para la prueba virtual no se anade automaticamente a un proyecto editable. Para eliminar imagenes descargadas o exportadas, borralas por separado de Fotos o Archivos y, si es necesario, de Eliminado recientemente.", "La version actual no requiere una cuenta Luverila. Por ello, no hay un perfil de cuenta que eliminar. Si una version futura introduce cuentas, esta pagina indicara como eliminarla antes de lanzar la funcion."], privacyBefore: "Para una solicitud de privacidad, contacta con", privacyAfter: "para obtener mas informacion.", privacyLink: "Politica de privacidad de la app",
    company: "Informacion de la empresa", operatedBy: "Luverila Hijab Designer es operada por:", lastUpdated: "Ultima actualizacion: 8 de agosto de 2026"
  },
  ar: {
    title: "الدعم", intro: "يساعد Luverila Hijab Designer المبدعين على رسم تصورات الحجاب وإنشاء تصميمات متعددة المشاهد وتوليد تصورات بالذكاء الاصطناعي وتجربة التصاميم على صورة شخصية مصرح بها وإعداد صور للمشاركة.",
    contact: "التواصل مع الدعم", contactLead: "للمساعدة، راسلنا على", include: "يرجى تضمين:", includeItems: ["طراز جهازك وإصدار iOS أو iPadOS", "إصدار تطبيق Luverila Hijab Designer", "وصف مختصر لما حدث", "لقطة شاشة للخطأ عند الاقتضاء"], sensitive: "يرجى عدم إرسال كلمات المرور أو رموز التحقق أو معلومات الدفع أو وثائق الهوية الحكومية أو مفاتيح API أو الصور الخاصة غير اللازمة للتحقيق في المشكلة عبر البريد الإلكتروني.", reply: "نهدف إلى الرد خلال يومي عمل إلى ثلاثة أيام عمل.",
    gettingStarted: "البدء", gettingItems: ["ابدئي تصميما جديدا أو افتحي مشروعا محفوظا.", "ارسمي ورتبي العناصر باستخدام الفرش والألوان والخامات والنقوش والطبقات والمناظر الأمامية أو الجانبية أو الخلفية.", "احفظي المشروع القابل للتعديل في مساحة الأعمال على الجهاز.", "صدري ملف PNG عندما تحتاجين إلى صورة نهائية.", "استخدمي التصور بالذكاء الاصطناعي أو التجربة الافتراضية فقط عندما ترغبين في معالجة التصميم المختار والصورة الشخصية الاختيارية بواسطة خدمة ذكاء اصطناعي."],
    saving: "حفظ التصميمات واستعادتها", savingText: "يتم تخزين مشاريع التصميم بشكل أساسي على جهازك. استخدمي حفظ المشروع لإنشاء عمل قابل للتعديل أو تحديثه في مساحة الأعمال. كما يمكنك تصدير ملف مشروع قابل للتعديل كنسخة احتياطية منفصلة.", important: "مهم:", savingItems: ["قد يؤدي حذف التطبيق أو مسح بياناته أو فقدان الجهاز أو استعادته إلى إزالة المشاريع المحفوظة محليا.", "ملف PNG هو صورة نهائية ولا يمكنه استعادة جميع الطبقات القابلة للتعديل.", "احتفظي بنسخ احتياطية مصدرة للمشاريع المهمة."],
    ai: "توليد الذكاء الاصطناعي غير متاح أو فشل", tryThis: "جربي ما يلي:", aiItems: ["تأكدي من أن جهازك متصل بالإنترنت بشكل مستقر.", "أبقي التطبيق مفتوحا أثناء إنشاء الصورة.", "حاولي لاحقا إذا كانت الخدمة مشغولة.", "قللي حجم الصور المستوردة الكبيرة جدا أو المواد المرجعية المعقدة.", "إن توفر ذلك، جربي خيار التوليد القياسي قبل التوليد عالي الجودة."], aiText: "قد يفشل توليد الذكاء الاصطناعي أحيانا أو ينتج نتيجة غير متوقعة. الصورة المولدة هي تصور بصري وليست ضمانا لمقاس المنتج النهائي أو صناعته أو لونه أو سلوك خامته.",
    tryOn: "التجربة الافتراضية وتشابه الوجه", bestResult: "لأفضل نتيجة:", tryOnItems: ["استخدمي صورة شخصية واضحة ومضاءة جيدا لشخص واحد", "حافظي على عدم حجب الوجه واستخدمي زاوية كاميرا طبيعية", "استخدمي منظرا للتصميم يظهر بنية الحجاب بوضوح", "فعلي حماية الهوية عندما تريدين أن يبقى الشخص قابلا للتعرف", "اجعلي تعديلات تكبير العينين وشكل الشفاه بدرجة معتدلة"], tryOnText: "قد يغير تحرير الصور بالذكاء الاصطناعي تفاصيل الوجه أو الوضعية أو موضع القماش أو الإضاءة. إذا لم تشبه النتيجة الشخص، فلا تشاركيها على أنها تمثيل دقيق. حاولي استخدام حماية هوية أقوى أو تعديلات تجميل أقل للوجه.", permission: "لا تحملي صورة شخصية إلا إذا كنت الشخص الظاهر فيها أو لديك إذنه.",
    sharing: "التصدير والمشاركة", sharingText: ["يمكنك تصدير الصور النهائية وإعداد صور مربعة أو عمودية أو بصيغة القصص للمشاركة. تظل الملفات المحفوظة في الصور أو الملفات هناك حتى تحذفيها باستخدام تطبيق Apple ذي الصلة.", "إذا لم تكن مشاركة النظام متاحة، نزلي صورة المشاركة ثم شاركيها من الصور أو الملفات."],
    delete: "حذف مشروع أو صورة", deleteText: ["لإزالة مشروع محفوظ، افتحي مساحة الأعمال واختاري حذف لهذا المشروع.", "لا تضاف الصورة الأصلية المختارة للتجربة الافتراضية تلقائيا إلى مشروع قابل للتعديل. لإزالة الصور التي تم تنزيلها أو تصديرها، احذفيها بشكل منفصل من الصور أو الملفات، وعند الحاجة من المحذوفة مؤخرا.", "لا يتطلب الإصدار الحالي حساب Luverila، لذلك لا يوجد ملف تعريف للحساب يمكن حذفه. إذا قدم إصدار مستقبلي حسابات، ستوفر هذه الصفحة طريقة حذف الحساب قبل إطلاق هذه الميزة."], privacyBefore: "لطلب متعلق بالخصوصية، تواصلي مع", privacyAfter: "للتفاصيل.", privacyLink: "سياسة خصوصية التطبيق",
    company: "معلومات الشركة", operatedBy: "تتم إدارة Luverila Hijab Designer بواسطة:", lastUpdated: "آخر تحديث: 8 أغسطس 2026"
  }
};

function List({ items, ordered = false }: { items: string[]; ordered?: boolean }) {
  const Tag = ordered ? "ol" : "ul";
  return <Tag>{items.map((item) => <li key={item}>{item}</li>)}</Tag>;
}

export function LocalizedAppSupport() {
  const { language } = useLanguage();
  const text = copy[language];
  const supportEmail = siteConfig.email;

  return <div className="shell app-support legal-copy">
    <div className="page-intro"><p className="eyebrow">Luverila Hijab Designer</p><h1>{text.title}</h1><p>{text.intro}</p></div>
    <section><h2>{text.contact}</h2><p>{text.contactLead} <a className="underline" href={`mailto:${supportEmail}`}>{supportEmail}</a>.</p><p>{text.include}</p><List items={text.includeItems} /><p>{text.sensitive}</p><p><strong>{text.reply}</strong></p></section>
    <section><h2>{text.gettingStarted}</h2><List items={text.gettingItems} ordered /></section>
    <section><h2>{text.saving}</h2><p>{text.savingText}</p><p><strong>{text.important}</strong></p><List items={text.savingItems} /></section>
    <section><h2>{text.ai}</h2><p>{text.tryThis}</p><List items={text.aiItems} ordered /><p>{text.aiText}</p></section>
    <section><h2>{text.tryOn}</h2><p>{text.bestResult}</p><List items={text.tryOnItems} /><p>{text.tryOnText}</p><p>{text.permission}</p></section>
    <section><h2>{text.sharing}</h2>{text.sharingText.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}</section>
    <section><h2>{text.delete}</h2>{text.deleteText.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}<p>{text.privacyBefore} <a className="underline" href={`mailto:${supportEmail}`}>{supportEmail}</a>. <Link className="underline" href="/app-privacy">{text.privacyLink}</Link> {text.privacyAfter}</p></section>
    <section><h2>{text.company}</h2><p>{text.operatedBy}</p><p><strong>{siteConfig.legalName}</strong><br /><strong>{siteConfig.address.replace(/, China$/, "")}</strong><br /><strong>China</strong></p><p className="support-updated">{text.lastUpdated}</p></section>
  </div>;
}
