import Image from "next/image";
import Link from "next/link";
import { ArrowDownRight, ArrowUpRight } from "lucide-react";
import { ProductCard } from "@/components/product/ProductCard";
import { SectionHeading } from "@/components/ui/SectionHeading";
import { getCollectionProducts } from "@/data/products";
import { editorialImages } from "@/lib/images";

export default function HomePage() {
  const bridal = getCollectionProducts("bridal").slice(0, 4);
  const hijab = getCollectionProducts("hijab").slice(0, 4);
  return <>
    <section className="hero">
      <div className="hero-media"><Image src={editorialImages.hero} alt="Editorial bridal fashion portrait" fill priority sizes="100vw" className="object-cover" /></div>
      <div className="hero-copy"><p className="hero-kicker">Bridal · Modest · Timeless</p><h1>Elegance Without Boundaries</h1><p className="hero-subtitle">Timeless bridal and modest fashion for modern women.</p><div className="hero-actions"><Link className="button button-light" href="/bridal">Explore bridal</Link><Link className="button button-light" href="/hijab">Explore hijabs</Link></div></div>
      <div className="absolute bottom-8 left-1/2 z-10 -translate-x-1/2 text-white"><ArrowDownRight size={22} strokeWidth={1} /></div>
    </section>
    <section className="section section-cream"><div className="shell"><SectionHeading eyebrow="A considered wardrobe" title="Two worlds. One language of elegance." /><div className="dual-feature"><div className="dual-panel" style={{ backgroundImage: `url(${editorialImages.dualBridal})`, backgroundSize:"cover", backgroundPosition:"center" }}><div className="dual-content"><p className="eyebrow text-white/70">Bridal</p><h3>Timeless silhouettes.</h3><p>Created for unforgettable moments, with a quiet point of view.</p><Link className="button button-light" href="/bridal">Explore bridal <ArrowUpRight size={14} /></Link></div></div><div className="dual-panel" style={{ backgroundImage: `url(${editorialImages.dualHijab})`, backgroundSize:"cover", backgroundPosition:"center" }}><div className="dual-content"><p className="eyebrow text-white/70">Modest</p><h3>Everyday grace.</h3><p>Modern hijabs designed with elegance and comfort in mind.</p><Link className="button button-light" href="/hijab">Explore hijabs <ArrowUpRight size={14} /></Link></div></div></div></div></section>
    <section className="section collection-section"><div className="shell"><SectionHeading eyebrow="Selected pieces" title="The bridal collection" intro="Luminous fabrics, thoughtful details and silhouettes that stay with you." /><div className="product-grid">{bridal.map((product) => <ProductCard key={product.id} product={product} />)}</div><div className="mt-12"><Link className="button button-ghost" href="/bridal">View all bridal pieces <ArrowUpRight size={14} /></Link></div></div></section>
    <section className="section section-cream collection-section"><div className="shell"><SectionHeading eyebrow="The modest collection" title="A softer kind of statement" intro="Contemporary scarves in refined tones, made for effortless elegance and everyday comfort." /><div className="product-grid">{hijab.map((product) => <ProductCard key={product.id} product={product} />)}</div><div className="mt-12"><Link className="button button-ghost" href="/hijab">View all hijabs <ArrowUpRight size={14} /></Link></div></div></section>
    <section className="section"><div className="shell about-split"><div className="about-image"><Image src={editorialImages.about} alt="Model wearing a refined modest fashion look" fill sizes="(max-width: 680px) 100vw, 50vw" className="object-cover" /></div><div className="about-copy"><SectionHeading eyebrow="Our point of view" title="About our company" /><p>We are a fashion company dedicated to creating elegant bridal and modest fashion collections.</p><p>Our collection brings together timeless wedding dresses, refined bridal pieces and contemporary hijabs, with a focus on thoughtful design, beautiful materials and modern femininity.</p><p>Through our work, we hope to create pieces that feel elegant, comfortable and meaningful for women around the world.</p><Link className="button button-dark mt-6" href="/about">Discover our story <ArrowUpRight size={14} /></Link></div></div></section>
    <section className="section section-cream"><div className="shell"><SectionHeading eyebrow="A visual diary" title="The lookbook" intro="A study in texture, light and the art of getting dressed." /><div className="lookbook-preview">{editorialImages.lookbook.slice(0,3).map((src, index) => <figure key={src}><Image src={src} alt={`Lookbook editorial image ${index + 1}`} fill sizes="(max-width: 680px) 33vw, 33vw" className="object-cover" /></figure>)}</div><div className="mt-12"><Link className="button button-ghost" href="/lookbook">View lookbook <ArrowUpRight size={14} /></Link></div></div></section>
    <section className="cta-band"><div className="shell"><SectionHeading eyebrow="Let's connect" title="Discover our collections or get in touch with our team." intro="We welcome product inquiries, collaborations and thoughtful conversations." /><Link className="button button-dark" href="/contact">Contact us <ArrowUpRight size={14} /></Link></div></section>
  </>;
}
