"use client";

import { ArrowUpRight } from "lucide-react";
import { PageText } from "@/components/i18n/PageText";
import { siteConfig } from "@/config/site";

export function ContactContent({ selectedProduct, subject, whatsappText }: { selectedProduct: string; subject: string; whatsappText: string }) {
  return <div className="shell"><div className="contact-grid"><section className="contact-copy"><div className="page-intro"><p className="eyebrow"><PageText id="contactUs" /></p><h1><PageText id="contactTitle" /></h1><p><PageText id="contactIntro" /></p></div><dl className="contact-details"><div><dt>Email</dt><dd><a href={`mailto:${siteConfig.email}`}>{siteConfig.email}</a></dd></div><div><dt>WhatsApp</dt><dd><a href={`https://wa.me/${siteConfig.whatsapp.replace(/\D/g, "")}`} target="_blank" rel="noreferrer">{siteConfig.whatsapp}</a></dd></div><div><dt>WeChat</dt><dd>{siteConfig.wechat}</dd></div><div><dt><PageText id="companyAddress" /></dt><dd>{siteConfig.address}</dd></div></dl></section><section><div className="page-intro"><p className="eyebrow"><PageText id="contactDirect" /></p><h2 className="font-serif text-4xl"><PageText id="startTeam" /></h2><p><PageText id="chooseContact" /></p></div>{selectedProduct && <p className="mb-6 text-sm text-muted"><PageText id="interestedProduct" />: <strong className="font-medium text-ink">{selectedProduct}</strong></p>}<div className="detail-actions"><a className="button button-dark" href={`mailto:${siteConfig.email}?subject=${encodeURIComponent(subject)}`}><PageText id="sendEmail" /> <ArrowUpRight size={14} /></a><a className="button button-ghost" href={`https://wa.me/${siteConfig.whatsapp.replace(/\D/g, "")}?text=${encodeURIComponent(whatsappText)}`} target="_blank" rel="noreferrer"><PageText id="whatsappContact" /> <ArrowUpRight size={14} /></a></div><div className="mt-10 border-t border-black/10 pt-8"><p className="eyebrow">WeChat</p><p className="font-serif text-3xl">{siteConfig.wechat}</p></div></section></div></div>;
}
